### ISSUE TITLE
Running tests in docker does not wait for completion

### ISSUE THREAD

**Issue by bmz1** [betaboon/vite-web-test-runner-plugin#6]
Hi! 
First of all, thank you for creating this plugin.

From the command line it works great, but I've tried running the tests with docker, and it actually doesn't wait for the tests to complete. I think this is because the vite dev server startup gives back a 0 exit code. This is just a guess though.

Have you tried this plugin in docker? If so, have you faced the same problem?

**Comment by betaboon** [comment]
hm. I am using it within github-ci which i believe is docker/osi based. could you provide a repro?

**Comment by bmz1** [comment]
@betaboon There you go: https://github.com/bmz1/vite-wtr-plugin-repro

**Comment by betaboon** [comment]
@bmz1 

adapted from [here](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker)

```diff
diff --git a/Dockerfile b/Dockerfile
index 28b322d..d25fb95 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -14,12 +14,6 @@ RUN apt-get update \
 ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
 ENV DOCKER=true

-COPY package.json yarn.lock /app/
+RUN npm i puppeteer

-RUN yarn install
-
-COPY . /app/
-
-RUN yarn test
-
-ENTRYPOINT [ "" ]
+CMD ["google-chrome-stable"]
diff --git a/package.json b/package.json
index a6a4067..25f8f0e 100644
--- a/package.json
+++ b/package.json
@@ -12,7 +12,9 @@
   "scripts": {
     "dev": "vite",
     "build": "vite build",
-    "test": "web-test-runner --coverage"
+    "test": "web-test-runner --coverage",
+    "docker-build": "docker build -t wtr:v1 .",
+    "docker-test": "docker run -i --init --rm -v $(pwd):/app wtr:v1 yarn test"
   },
   "dependencies": {
     "lit-element": "^2.4.0"
```

**Comment by bmz1** [comment]
@betaboon My problem is not running puppeteer, but the following:
![test](https://i.imgur.com/1QhcrCg.png)

When I run the tests with the same Dockerfile without the plugin, it waits for the tests to finish.
But somehow it does not wait with the plugin.

**Comment by betaboon** [comment]
tbh I'm not sure if it's the right approach to run the tests in the build-phase of a docker image oO

**Comment by IanVS** [comment]
I'm having this same problem as well, in Github actions.

@betaboon if it's working for you, what versions of web-test-runner and vite are you using?

**Comment by betaboon** [comment]
@IanVS that issue/codepath is a nice find. that would completly explain the behavior.
I'm perplexed why it works in my github-actions tho.
```
"@web/test-runner": "^0.13.3",
"chai": "^4.3.4",
"vite": "^2.2.3",
```

But i currently don't have the time to look into it. so thank you very much for spending the time and working on a solution :)

**Comment by bmz1** [comment]
https://github.com/vitejs/vite/pull/3659

**Comment by IanVS** [comment]
@bmz1 after a new version of vite is released, it would be great if you could check that it solves your issue.

**Comment by IanVS** [comment]
`vite@2.4.0-beta.0` has been released with the referenced PR.  Does it solve your problem, @bmz1?

**Comment by bmz1** [comment]
@IanVS Yes it does 🍾 . Setting `ENV CI=true` in the Dockerfile solves it. Thanks for your cooperation.

**Comment by IanVS** [comment]
🎉 should this issue be closed, then?

**Comment by betaboon** [comment]
perfect. thank you guys for following up :)
