### ISSUE TITLE
Prevent "[vite] connecting..." logs

### ISSUE THREAD

**Issue by IanVS** [betaboon/vite-web-test-runner-plugin#7]
I think I've gotten my tests running correctly, but for every test, I see:

```
 🚧 Browser logs:
      [vite] connecting...
      [vite] connected.
```

Is it possible to silence those?  I've tried `logLevel: 'silent'` in my vite.config.ts, with no luck.

**Comment by IanVS** [comment]
I think this is an issue in vite, and have opened an issue there.  https://github.com/vitejs/vite/issues/3641

**Comment by betaboon** [comment]
thanks for letting us know and looking into it.
I would reopen this issue to keep track of it ;)

**Comment by betaboon** [comment]
thanks for following up. merged ;)
