### ISSUE TITLE
no such file or directory, open 'node_modules/vite/src/client/env.ts'

### ISSUE THREAD

**Issue by IanVS** [betaboon/vite-web-test-runner-plugin#8]
My tests all fail with the error message:

```
[vite] Internal server error: ENOENT: no such file or directory, open 'node_modules/vite/src/client/env.ts'
```

... unless I go into my node_modules and delete `node_modules/vite/dist/client/env.js.map`.  Is this a problem in vite, or this plugin?  I'm brand new to both.

Thanks!

**Comment by betaboon** [comment]
i never saw this happen. can you provide a repro?

**Comment by IanVS** [comment]
Sure, here you are!  https://github.com/IanVS/vite-wtr-issue-8

**Comment by IanVS** [comment]
OK, I have a good reproduction now.  If you `npm i` and then `npm test`, you should see the error I mention above.  Then, if you go into your node_modules and delete the map file, the test will pass.

**Comment by betaboon** [comment]
I'm sorry the repro won't run on my system as the binary-packages for browsers playwright downloads do not work on my system

**Comment by IanVS** [comment]
OK, I've switched to puppeteer, which still reproduces the issue for me.

**Comment by betaboon** [comment]
with that i can reproduce it. i feel like this an issue of vite. but not sure. maybe ask in their discord ? oO

**Comment by IanVS** [comment]
This has been fixed in recent versions of vite.

**Comment by betaboon** [comment]
awesome. thanks for reporting back
